// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: assets/bank.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BankSlipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Person  string `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
	Value   int64  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	DueDate bool   `protobuf:"varint,3,opt,name=dueDate,proto3" json:"dueDate,omitempty"`
}

func (x *BankSlipRequest) Reset() {
	*x = BankSlipRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_assets_bank_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BankSlipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankSlipRequest) ProtoMessage() {}

func (x *BankSlipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assets_bank_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankSlipRequest.ProtoReflect.Descriptor instead.
func (*BankSlipRequest) Descriptor() ([]byte, []int) {
	return file_assets_bank_proto_rawDescGZIP(), []int{0}
}

func (x *BankSlipRequest) GetPerson() string {
	if x != nil {
		return x.Person
	}
	return ""
}

func (x *BankSlipRequest) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *BankSlipRequest) GetDueDate() bool {
	if x != nil {
		return x.DueDate
	}
	return false
}

//
type BankSlipReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *BankSlipReply) Reset() {
	*x = BankSlipReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_assets_bank_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BankSlipReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankSlipReply) ProtoMessage() {}

func (x *BankSlipReply) ProtoReflect() protoreflect.Message {
	mi := &file_assets_bank_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankSlipReply.ProtoReflect.Descriptor instead.
func (*BankSlipReply) Descriptor() ([]byte, []int) {
	return file_assets_bank_proto_rawDescGZIP(), []int{1}
}

func (x *BankSlipReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_assets_bank_proto protoreflect.FileDescriptor

var file_assets_bank_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2f, 0x62, 0x61, 0x6e, 0x6b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x62, 0x61, 0x6e, 0x6b, 0x22, 0x59, 0x0a, 0x0f, 0x42, 0x61, 0x6e,
	0x6b, 0x53, 0x6c, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x75,
	0x65, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x64, 0x75, 0x65,
	0x44, 0x61, 0x74, 0x65, 0x22, 0x29, 0x0a, 0x0d, 0x42, 0x61, 0x6e, 0x6b, 0x53, 0x6c, 0x69, 0x70,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32,
	0x48, 0x0a, 0x04, 0x42, 0x61, 0x6e, 0x6b, 0x12, 0x40, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x42, 0x61, 0x6e, 0x6b, 0x53, 0x6c, 0x69, 0x70, 0x12, 0x15, 0x2e, 0x62, 0x61,
	0x6e, 0x6b, 0x2e, 0x42, 0x61, 0x6e, 0x6b, 0x53, 0x6c, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x13, 0x2e, 0x62, 0x61, 0x6e, 0x6b, 0x2e, 0x42, 0x61, 0x6e, 0x6b, 0x53, 0x6c,
	0x69, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x38, 0x5a, 0x36, 0x63, 0x6f, 0x6d,
	0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2f, 0x72, 0x61, 0x66, 0x61, 0x65, 0x6c, 0x77, 0x61,
	0x74, 0x65, 0x72, 0x6b, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x72, 0x70,
	0x63, 0x2d, 0x6b, 0x61, 0x66, 0x6b, 0x61, 0x2d, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x61, 0x70, 0x70,
	0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_assets_bank_proto_rawDescOnce sync.Once
	file_assets_bank_proto_rawDescData = file_assets_bank_proto_rawDesc
)

func file_assets_bank_proto_rawDescGZIP() []byte {
	file_assets_bank_proto_rawDescOnce.Do(func() {
		file_assets_bank_proto_rawDescData = protoimpl.X.CompressGZIP(file_assets_bank_proto_rawDescData)
	})
	return file_assets_bank_proto_rawDescData
}

var file_assets_bank_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_assets_bank_proto_goTypes = []interface{}{
	(*BankSlipRequest)(nil), // 0: bank.BankSlipRequest
	(*BankSlipReply)(nil),   // 1: bank.BankSlipReply
}
var file_assets_bank_proto_depIdxs = []int32{
	0, // 0: bank.Bank.RegisterBankSlip:input_type -> bank.BankSlipRequest
	1, // 1: bank.Bank.RegisterBankSlip:output_type -> bank.BankSlipReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_assets_bank_proto_init() }
func file_assets_bank_proto_init() {
	if File_assets_bank_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_assets_bank_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BankSlipRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_assets_bank_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BankSlipReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_assets_bank_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_assets_bank_proto_goTypes,
		DependencyIndexes: file_assets_bank_proto_depIdxs,
		MessageInfos:      file_assets_bank_proto_msgTypes,
	}.Build()
	File_assets_bank_proto = out.File
	file_assets_bank_proto_rawDesc = nil
	file_assets_bank_proto_goTypes = nil
	file_assets_bank_proto_depIdxs = nil
}
