// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: assets/inventory.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AvailabilityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Product  string `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Quantity int64  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Book     bool   `protobuf:"varint,3,opt,name=book,proto3" json:"book,omitempty"`
}

func (x *AvailabilityRequest) Reset() {
	*x = AvailabilityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_assets_inventory_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailabilityRequest) ProtoMessage() {}

func (x *AvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assets_inventory_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailabilityRequest.ProtoReflect.Descriptor instead.
func (*AvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_assets_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *AvailabilityRequest) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *AvailabilityRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AvailabilityRequest) GetBook() bool {
	if x != nil {
		return x.Book
	}
	return false
}

//
type AvailabilityReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Available int64  `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Booked    string `protobuf:"bytes,2,opt,name=booked,proto3" json:"booked,omitempty"`
}

func (x *AvailabilityReply) Reset() {
	*x = AvailabilityReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_assets_inventory_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvailabilityReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailabilityReply) ProtoMessage() {}

func (x *AvailabilityReply) ProtoReflect() protoreflect.Message {
	mi := &file_assets_inventory_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailabilityReply.ProtoReflect.Descriptor instead.
func (*AvailabilityReply) Descriptor() ([]byte, []int) {
	return file_assets_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *AvailabilityReply) GetAvailable() int64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *AvailabilityReply) GetBooked() string {
	if x != nil {
		return x.Booked
	}
	return ""
}

var File_assets_inventory_proto protoreflect.FileDescriptor

var file_assets_inventory_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2f, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f,
	0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74,
	0x6f, 0x72, 0x79, 0x22, 0x5f, 0x0a, 0x13, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04,
	0x62, 0x6f, 0x6f, 0x6b, 0x22, 0x49, 0x0a, 0x11, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x61, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x65,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x65, 0x64, 0x32,
	0x60, 0x0a, 0x09, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x53, 0x0a, 0x11,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x12, 0x1e, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x41, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x41, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x42, 0x38, 0x5a, 0x36, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2f,
	0x72, 0x61, 0x66, 0x61, 0x65, 0x6c, 0x77, 0x61, 0x74, 0x65, 0x72, 0x6b, 0x65, 0x6d, 0x70, 0x65,
	0x72, 0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x6b, 0x61, 0x66, 0x6b, 0x61, 0x2d,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x61, 0x70, 0x70, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_assets_inventory_proto_rawDescOnce sync.Once
	file_assets_inventory_proto_rawDescData = file_assets_inventory_proto_rawDesc
)

func file_assets_inventory_proto_rawDescGZIP() []byte {
	file_assets_inventory_proto_rawDescOnce.Do(func() {
		file_assets_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(file_assets_inventory_proto_rawDescData)
	})
	return file_assets_inventory_proto_rawDescData
}

var file_assets_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_assets_inventory_proto_goTypes = []interface{}{
	(*AvailabilityRequest)(nil), // 0: inventory.AvailabilityRequest
	(*AvailabilityReply)(nil),   // 1: inventory.AvailabilityReply
}
var file_assets_inventory_proto_depIdxs = []int32{
	0, // 0: inventory.Inventory.CheckAvailability:input_type -> inventory.AvailabilityRequest
	1, // 1: inventory.Inventory.CheckAvailability:output_type -> inventory.AvailabilityReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_assets_inventory_proto_init() }
func file_assets_inventory_proto_init() {
	if File_assets_inventory_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_assets_inventory_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvailabilityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_assets_inventory_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvailabilityReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_assets_inventory_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_assets_inventory_proto_goTypes,
		DependencyIndexes: file_assets_inventory_proto_depIdxs,
		MessageInfos:      file_assets_inventory_proto_msgTypes,
	}.Build()
	File_assets_inventory_proto = out.File
	file_assets_inventory_proto_rawDesc = nil
	file_assets_inventory_proto_goTypes = nil
	file_assets_inventory_proto_depIdxs = nil
}
